export enum CountryCodes {
  POL = "Poland",
  ROU = "Romania",
  USA = "USA",
  FRA = "France",
  ITA = "Italy",
  HUN = "Hungary",
  ESP = "Spain",
  SVN = "Slovenia",
  HRV = "Croatia",
  TUR = "Turkey",
  GBR = "United Kingdom",
  LTU = "Lithuania",
  NLD = "Netherlands",
}

export enum CountryCodeMapping {
  pl = "POL",
  ro = "ROU",
  us = "USA",
  fr = "FRA",
  it = "ITA",
  en = "GBR",

  hu = "HUN",
  es = "ESP",
  sv = "SVN",
  hr = "HRV",
  tr = "TUR",
  lt = "LTU",
  nl = "NLD",

  // de = "DEU",
  // be = "BEL",
  // es = "ESP",

  //List of i18n available languages
  // af = "af",
  // sq = "sq",
  // ar = "ar",
  // eu = "eu",
  // bg = "bg",
  // be = "be",
  // ca = "ca",
  // hr = "hr",
  // cs = "cs",
  // da = "da",
  // nl = "nl",
  // eo = "eo",
  // et = "et",
  // fo = "fo",
  // fi = "fi",
  // gl = "gl",
  // de = "de",
  // el = "el",
  // iw = "iw",
  // hu = "hu",
  // is = "is",
  // ga = "ga",
  // ja = "ja",
  // ko = "ko",
  // lv = "lv",
  // lt = "lt",
  // mk = "mk",
  // mt = "mt",
  // no = "no",
  // pt = "pt",
  // ru = "ru",
  // gd = "gd",
  // sk = "sk",
  // sl = "sl",
  // es = "es",
  // sv = "sv",
  // tr = "tr",
  // uk = "uk",
}

export function getMappedCountryCode(countryCode: string): keyof typeof CountryCodes {
  return CountryCodeMapping[countryCode as keyof typeof CountryCodeMapping];
}
